-- Custom Defines for Gulyaipole (GLP) Mod
NDefines.NDiplomacy.WARGOAL_JUSTIFY_TENSION_LIMIT = 0.03
NDefines.NDiplomacy.SEND_VOLUNTEERS_TENSION_LIMIT = 0.00
NDefines.NDiplomacy.SEND_VOLUNTEERS_RULES_TENSION = 0.00
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 1
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.5
